### ISSUE TITLE
use rental to eliminate bookkeeping

### ISSUE THREAD

**Issue by durka** [durka/owned-chars#2]
Using [rental](https://docs.rs/rental) we should be able to directly store `Chars`/`CharIndices` and remove the slicing and arithmetic.

Assigned to @doomrobo.

**Comment by rozbb** [comment]
This ended up being more difficult than expected.

The first problem is that, in order to `impl Clone`, we need access to the underlying `String`. This is easy with the `RentRef::owner` method. However, we _also_ need the `RentMut::rent_mut` method, since the internal `Chars::next` takes a `&mut self`. Herein lies the problem. The rental type can either be `RentRef` or `RentMut`, but not both. `RentRef` does not implement `rent_mut()` for obvious reasons, and `RentMut` does not implement `owner()`, for safety reasons. A solution here would require more unsafety.

The second problem also comes up when we implement `Clone`. In order to make a new `Chars` iterator that's in the same position as the original one, we need to call `skip()` or at least loop `next()` a few times. The problem is that this requires the exact bookkeeping that we're trying to avoid in the first place. Furthermore, `skip()` actually returns a `Skip<Chars<'a>>` which is _not_ compatible with the rental type `Chars<'a>` or even something like `S: Iterator, S<'a>`.

Given these problems, I think using rental would introduce more complexity than it saves. Vote to close

**Comment by durka** [comment]
Belatedly closed by #4.
